#
# Copyright © 2016-2019 The Thingsboard Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: '2.2'

services:
  postgres:
    restart: always
    image: "postgres:9.6"
    ports:
    - "5432"
    environment:
      POSTGRES_DB: thingsboard
    volumes:
      - ./navity-node/postgres:/var/lib/postgresql/data
  navity1:
    env_file:
      - navity-node.postgres.env
    depends_on:
      - kafka
      - redis
      - postgres
  navity2:
    env_file:
      - navity-node.postgres.env
    depends_on:
      - kafka
      - redis
      - postgres
